---
title: "GTFOArgs: Argument Injection Exploitation Vector List"
description: >-
  GTFOArgs is a curated list of Unix binaries whose arguments can be exploited
  for argument injection, enabling shell escapes, privilege escalation,
  file read/write, and other post-exploitation techniques.
url: "https://gtfoargs.github.io"
permalink: pretty
logo: /assets/logo.png

author:
  name: Joshua Rogers
  url: "https://joshua.hu/"

twitter:
  username: megamansec
  card: summary

social:
  name: Joshua Rogers
  links:
    - https://x.com/megamansec
    - https://www.linkedin.com/in/joshua-alexander-rogers
    - https://github.com/GTFOArgs

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - /scripts
  - /Gemfile
  - /Makefile
  - /README.md
  - /CONTRIBUTING.md

collections:
  gtfoargs:
    output: true

defaults:
  - scope:
      path: "_gtfoargs"
    values:
      layout: bin
  - scope:
      path: ""
    values:
      image: /assets/logo.png
