---
title: "GTFOArgs: Argument Injection Exploitation Vector List"

include:
  - llms.txt
  - llms-full.txt

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md', '/CONTRIBUTING.md']

permalink: pretty

collections:
  gtfoargs:
    output: true

defaults:
  - scope:
      path: '_gtfoargs'
    values:
      layout: bin
